###
GET http://localhost:8000/api/products
Accept: application/json

###

POST http://localhost:8000/api/products
Content-Type: application/json

{
  "title": "Teste",
  "image": "aaaaaa",
  "price": 13.12
}

###
GET http://localhost:8000/api/products/1
Accept: application/json

###

###
PUT http://localhost:8000/api/products/1
Content-Type: application/json

{
  "title": "Teste2",
  "image": "aaaaaa",
  "price": 13.12
}

###

DELETE http://localhost:8000/api/products/1

###
