version: "3"

services:
  web:
    build: .
    container_name: "web-django-server"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/app
    ports:
      - 8000:8000
    networks:
      - postgres
    env_file:
      - ./.env
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:13.0-alpine
    container_name: "postgres-db-django-server"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - postgres
    env_file:
      - ./.env

  rabbitmq:
    container_name: "rabbitmq-django-server"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=test
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    networks:
      - postgres

  pgadmin:
    container_name: "pgadmin-django-server"
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin:

networks:
  postgres:
    driver: bridge
