version: "3"

services:
  app:
    build: .
    container_name: "flask-dev-server"
    depends_on:
      - db
    networks:
      - postgres
    ports:
      - 5000:5000
    volumes:
      - .:/home/flask
      - ./app:/home/flask/app
      - ./migrations:/home/flask/migrations
    env_file:
      - ./.env

  db:
    image: postgres:13.0-alpine
    container_name: "postgres-db-server"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - postgres
    env_file:
      - ./.env
    restart: always

  pgadmin:
    container_name: "pgadmin-flask-server"
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  postgres_data:
  pgadmin:

networks:
  postgres:
    driver: bridge
